/home/pi/src/HangarBuddy/hangar_buddy.log {
    rotate 7
    daily
    notifempty
    missingok
    copytruncate
}

/home/pi/src/HangarBuddy/sensors.log {
    rotate 7
    daily
    notifempty
    missingok
    copytruncate
}